import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:3003/login', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
const bg = await page.evaluate(() => getComputedStyle(document.body).backgroundColor);
console.log('Body background:', bg);
const dark = bg === 'rgb(6, 15, 30)' || bg.includes('rgb(6');
console.log(dark ? 'PASS Dark theme' : 'FAIL: ' + bg);
await browser.close();
