/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue access + refresh token */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Bad credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke caller's refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clinical/denture-cases": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        /** List denture cases */
        get: {
            parameters: {
                query?: {
                    patient_id?: string;
                    status?: "open" | "closed";
                    stage?: string;
                };
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DentureCase"][];
                    };
                };
            };
        };
        put?: never;
        /** Open a denture case */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        patient_id: string;
                        arch: string;
                        case_type: string;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DentureCase"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clinical/denture-cases/{id}/advance": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance case stage */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        stage: string;
                        note?: string;
                        photo_document_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DentureCase"];
                    };
                };
                /** @description Invalid transition */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/lab/cases": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        /** List lab cases */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    vendor_id?: string;
                    denture_case_id?: string;
                };
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabCase"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a lab case (status=draft) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        denture_case_id: string;
                        vendor_id: string;
                        /** Format: date-time */
                        due_back_at?: string;
                        lab_fee?: number;
                        courier_tracking?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabCase"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/lab/cases/{id}/remake": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a lab case as remake; returns the new child case */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabCase"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/treatment-plans": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a treatment plan */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        patient_id: string;
                        items: {
                            procedure_code: string;
                            description?: string;
                            fee?: number;
                            insurance_coverage_pct?: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TreatmentPlan"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/billing/invoices": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create draft invoice */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        patient_id: string;
                        appointment_id?: string;
                        treatment_plan_id?: string;
                        gst_rate?: number;
                        lines: {
                            procedure_code: string;
                            description?: string;
                            qty: number;
                            unit_price: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invoice"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/billing/invoices/{id}/payments": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a payment against an invoice */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        method: string;
                        amount: number;
                        reference?: string;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/insurance/claims": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create draft claim or predetermination */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        invoice_id: string;
                        carrier: string;
                        /** @enum {string} */
                        kind: "predetermination" | "claim";
                        assignment_of_benefits?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InsuranceClaim"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/communications/send": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send an SMS or email to a patient */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        patient_id: string;
                        /** @enum {string} */
                        channel: "sms" | "email";
                        body: string;
                        related_appointment_id?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Communication"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/crm/leads/{id}/convert": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert a lead to a patient (idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default true */
                        create_patient?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            lead_id: string;
                            patient_id: string;
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/admin/audit-log": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        /** Paginated audit log */
        get: {
            parameters: {
                query?: {
                    entity_type?: string;
                    entity_id?: string;
                    user_id?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditLogEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clinical/documents/upload": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a document (multipart); deduplicates by sha256 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /** @enum {string} */
                        kind: "photo" | "xray" | "consent" | "other";
                        patient_id: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentUpload"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clinical/patients/{patient_id}/tooth-chart": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        /** Get tooth chart (always 32 entries) */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    patient_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToothChartEntry"][];
                    };
                };
            };
        };
        put?: never;
        /** Upsert tooth chart entries (partial) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    patient_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ToothChartEntryIn"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToothChartEntry"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clinical/patients/{patient_id}/insurance/{insurance_id}": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                patient_id: string;
                insurance_id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a patient insurance record */
        put: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    patient_id: string;
                    insurance_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InsuranceIn"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PatientInsurance"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a patient insurance record */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    patient_id: string;
                    insurance_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clinical/denture-cases/{case_id}/implants": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        /** List implants for a denture case */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    case_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DentureCaseImplant"][];
                    };
                };
            };
        };
        put?: never;
        /** Add an implant to a denture case */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    case_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DentureCaseImplantIn"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DentureCaseImplant"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/billing/invoices/from-plan": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a draft invoice from a treatment plan */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InvoiceFromPlanIn"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invoice"];
                    };
                };
                /** @description Treatment plan not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/crm/leads": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new lead */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        first_name: string;
                        last_name: string;
                        phone: string;
                        email?: string | null;
                        source?: string | null;
                        notes?: string | null;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeadOut"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/crm/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Partial update a lead (owner_id, status, notes, etc.) */
        put: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    lead_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        owner_id?: string | null;
                        status?: string | null;
                        notes?: string | null;
                        first_name?: string | null;
                        last_name?: string | null;
                        phone?: string | null;
                        email?: string | null;
                        source?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeadOut"];
                    };
                };
                /** @description Lead not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/crm/leads/{lead_id}/activities": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        /** List activities for a lead, sorted by created_at DESC */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    lead_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeadActivity"][];
                    };
                };
                /** @description Lead not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create an activity (note/call/email/meeting) for a lead */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    lead_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        kind: "note" | "call" | "email" | "meeting";
                        body: string;
                        payload?: Record<string, never> | null;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeadActivity"];
                    };
                };
                /** @description Lead not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clinical/appointments/{appointment_id}": {
        parameters: {
            query?: never;
            header?: {
                "X-Clinic-Id"?: components["parameters"]["XClinicId"];
            };
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        /** Get appointment by ID (v2 — includes chief_complaint) */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Clinic-Id"?: components["parameters"]["XClinicId"];
                };
                path: {
                    appointment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppointmentV2"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            detail: string | Record<string, never>;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @description seconds */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        User: {
            id: string;
            clinic_id: string;
            /** Format: email */
            email: string;
            full_name: string;
            is_active: boolean;
            roles?: string[];
            permissions?: string[];
        };
        PatientInsurance: {
            id?: string;
            carrier: string;
            policy_number: string;
            group_number?: string | null;
            holder_name: string;
            holder_relationship?: string | null;
            /** @default false */
            assignment_of_benefits: boolean;
            coverage_pct_by_category?: {
                [key: string]: number;
            };
            /** Format: date */
            valid_from?: string | null;
            /** Format: date */
            valid_to?: string | null;
            is_primary: boolean;
        };
        Document: {
            id?: string;
            /** @enum {string} */
            kind: "photo" | "xray" | "consent" | "other";
            /** Format: uri */
            storage_url: string;
            content_sha256: string;
            mime: string;
            size_bytes: number;
            uploaded_by?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        ClinicalNote: {
            id?: string;
            patient_id: string;
            appointment_id?: string | null;
            author_id?: string | null;
            soap_subjective?: string;
            soap_objective?: string;
            soap_assessment?: string;
            soap_plan?: string;
            /** Format: date-time */
            locked_at?: string | null;
            supersedes_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        DentureCase: {
            id?: string;
            patient_id: string;
            /** @enum {string} */
            arch: "upper" | "lower" | "both";
            /** @enum {string} */
            case_type: "complete" | "partial" | "immediate" | "implant_retained";
            /** @enum {string} */
            current_stage: "consult" | "prelim_imp" | "final_imp" | "bite_reg" | "wax_tryin" | "insert" | "adjust" | "complete" | "cancelled";
            /** @enum {string} */
            status: "open" | "closed";
            /** Format: date-time */
            opened_at?: string;
            /** Format: date-time */
            closed_at?: string | null;
            notes?: string | null;
        };
        DentureCaseEvent: {
            id?: string;
            case_id?: string;
            stage?: string;
            /** Format: date-time */
            occurred_at?: string;
            provider_id?: number | null;
            note?: string | null;
            photo_document_ids?: string[];
        };
        LabVendor: {
            id?: string;
            name: string;
            /** Format: email */
            contact_email?: string | null;
            contact_phone?: string | null;
            sla_days?: number | null;
            /** @default true */
            is_active: boolean;
        };
        LabCase: {
            id?: string;
            denture_case_id: string;
            vendor_id: string;
            /** Format: date-time */
            sent_at?: string | null;
            /** Format: date-time */
            due_back_at?: string | null;
            /** Format: date-time */
            returned_at?: string | null;
            /** @enum {string} */
            status: "draft" | "sent" | "in_progress" | "returned" | "remake" | "cancelled";
            remake_of_id?: string | null;
            remake_reason?: string | null;
            lab_fee?: number | null;
            courier_tracking?: string | null;
        };
        Procedure: {
            id?: string;
            /** @description ADA&C code */
            code: string;
            name: string;
            default_duration_min?: number | null;
            default_fee?: number | null;
            /** @enum {string} */
            category?: "preventive" | "diagnostic" | "restorative" | "prosthodontic" | "periodontic" | "surgical" | "other";
        };
        TreatmentPlan: {
            id?: string;
            patient_id: string;
            /** @enum {string} */
            status: "draft" | "presented" | "accepted" | "in_progress" | "completed" | "declined";
            total_estimate?: number;
            insurance_estimate?: number;
            patient_estimate?: number;
            items?: components["schemas"]["TreatmentPlanItem"][];
        };
        TreatmentPlanItem: {
            id?: string;
            sequence?: number;
            procedure_code: string;
            description?: string | null;
            fee: number;
            insurance_coverage_pct?: number | null;
            /** Format: date-time */
            completed_at?: string | null;
        };
        Operatory: {
            id?: string;
            name: string;
            equipment_tags?: string[];
            /** @default true */
            is_active: boolean;
        };
        Invoice: {
            id?: string;
            patient_id: string;
            appointment_id?: string | null;
            treatment_plan_id?: string | null;
            /** @enum {string} */
            status: "draft" | "issued" | "partial" | "paid" | "void";
            subtotal: number;
            gst: number;
            total: number;
            balance: number;
            /** @default CAD */
            currency: string;
            /** Format: date-time */
            issued_at?: string | null;
            /** Format: date-time */
            due_at?: string | null;
            lines?: components["schemas"]["InvoiceLine"][];
        };
        InvoiceLine: {
            id?: string;
            sequence?: number;
            procedure_code: string;
            description?: string | null;
            qty: number;
            unit_price: number;
            total: number;
        };
        Payment: {
            id?: string;
            /** @enum {string} */
            method: "cash" | "card" | "cheque" | "etransfer" | "insurance";
            amount: number;
            /** Format: date-time */
            received_at: string;
            reference?: string | null;
            notes?: string | null;
        };
        InsuranceClaim: {
            id?: string;
            invoice_id: string;
            carrier: string;
            /** @enum {string} */
            kind: "predetermination" | "claim";
            assignment_of_benefits?: boolean;
            /** @enum {string} */
            status: "draft" | "submitted" | "accepted" | "adjudicated" | "paid" | "rejected" | "partial";
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            adjudicated_at?: string | null;
            /** Format: date-time */
            paid_at?: string | null;
            response_payload?: Record<string, never> | null;
        };
        Communication: {
            id?: string;
            patient_id: string;
            /** @enum {string} */
            channel: "sms" | "email" | "inbound_sms" | "inbound_email";
            /** @enum {string} */
            direction: "out" | "in";
            body: string;
            /** @enum {string} */
            status: "queued" | "sent" | "delivered" | "failed" | "received";
            related_appointment_id?: string | null;
            related_invoice_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            sent_at?: string | null;
        };
        LeadEvent: {
            id?: string;
            lead_id: string;
            /** @enum {string} */
            kind: "note" | "status_change" | "email_sent" | "sms_sent" | "converted";
            /** Format: date-time */
            occurred_at: string;
            payload?: Record<string, never>;
        };
        AuditLogEntry: {
            id: string;
            clinic_id?: string;
            user_id?: string | null;
            action: string;
            entity_type: string;
            entity_id: string;
            before?: Record<string, never> | null;
            after?: Record<string, never> | null;
            ip?: string | null;
            user_agent?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        DocumentUpload: {
            id: string;
            storage_url: string;
            sha256: string;
            mime_type?: string | null;
            size_bytes?: number | null;
            /** @enum {string} */
            kind: "photo" | "xray" | "consent" | "other";
            patient_id: string;
            deduped: boolean;
        };
        ToothChartEntry: {
            tooth_number: number;
            status: string;
            surface_notes?: Record<string, never> | null;
        };
        ToothChartEntryIn: {
            tooth_number: number;
            status: string;
            surface_notes?: Record<string, never> | null;
        };
        InsuranceIn: {
            carrier: string;
            policy_number?: string | null;
            group_number?: string | null;
            holder_name?: string | null;
            holder_relationship?: string | null;
            /** @default false */
            assignment_of_benefits: boolean;
            coverage_pct_by_category?: {
                [key: string]: number;
            };
            /** Format: date-time */
            valid_from?: string | null;
            /** Format: date-time */
            valid_to?: string | null;
            /** @default false */
            is_primary: boolean;
        };
        DentureCaseImplant: {
            id: string;
            denture_case_id: string;
            tooth_position: number;
            vendor: string;
            model?: string | null;
            lot_number: string;
            surface_treatment?: string | null;
            abutment_type?: string | null;
            /** Format: date */
            placed_date?: string | null;
        };
        DentureCaseImplantIn: {
            tooth_position: number;
            vendor: string;
            model?: string | null;
            lot_number: string;
            surface_treatment?: string | null;
            abutment_type?: string | null;
            /** Format: date */
            placed_date?: string | null;
        };
        InvoiceFromPlanIn: {
            treatment_plan_id: string;
            patient_id: string;
            /** @default 0.05 */
            gst_rate: number;
        };
        LeadOut: {
            id: string;
            clinic_id: string;
            name?: string | null;
            first_name?: string | null;
            last_name?: string | null;
            phone: string;
            email?: string | null;
            source?: string | null;
            status?: string;
            notes?: string | null;
            owner_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        LeadActivity: {
            id: string;
            lead_id: string;
            /** @enum {string} */
            kind: "note" | "call" | "email" | "meeting";
            body?: string | null;
            /** Format: date-time */
            occurred_at: string;
            payload?: Record<string, never> | null;
        };
        AppointmentV2: {
            id: string;
            patient_id: string;
            provider_id: number;
            service_id?: number | null;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            reason_note?: string | null;
            chief_complaint?: string | null;
            status: string;
        };
    };
    responses: never;
    parameters: {
        XClinicId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
