"""track4_schema_v1_1_denturist_polish

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2026-05-02 03:08:43.899219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_closures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_closures_clinic_id'), 'clinic_closures', ['clinic_id'], unique=False)
    op.create_index('ix_clinic_closures_clinic_start', 'clinic_closures', ['clinic_id', 'start_date'], unique=False)
    op.create_table('clinic_operating_hours',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_at', sa.Time(), nullable=False),
    sa.Column('close_at', sa.Time(), nullable=False),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'day_of_week', name='ux_clinic_hours_clinic_dow')
    )
    op.create_index(op.f('ix_clinic_operating_hours_clinic_id'), 'clinic_operating_hours', ['clinic_id'], unique=False)
    op.create_table('clinic_sequences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('sequence_kind', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'sequence_kind', 'year', name='ux_clinic_sequence_clinic_kind_year')
    )
    op.create_index('ix_clinic_sequences_clinic_kind', 'clinic_sequences', ['clinic_id', 'sequence_kind'], unique=False)
    op.create_table('human_identifiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'kind', 'value', name='ux_humanid_clinic_kind_value'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'kind', name='ux_humanid_entity_kind')
    )
    op.create_index('ix_human_identifiers_clinic_kind', 'human_identifiers', ['clinic_id', 'kind'], unique=False)
    op.create_index('ix_human_identifiers_entity', 'human_identifiers', ['entity_type', 'entity_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('reorder_threshold', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'sku', name='ux_inventory_item_clinic_sku')
    )
    op.create_index(op.f('ix_inventory_items_clinic_id'), 'inventory_items', ['clinic_id'], unique=False)
    op.create_table('inventory_lots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('qty_received', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('qty_on_hand', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('supplier_batch_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('quarantined_at', sa.DateTime(), nullable=True),
    sa.Column('quarantine_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'lot_number', name='ux_inventory_lot_item_lotno')
    )
    op.create_index(op.f('ix_inventory_lots_clinic_id'), 'inventory_lots', ['clinic_id'], unique=False)
    op.create_index('ix_inventory_lots_clinic_qty', 'inventory_lots', ['clinic_id', 'qty_on_hand'], unique=False)
    op.create_index(op.f('ix_inventory_lots_item_id'), 'inventory_lots', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_lots_lot_number'), 'inventory_lots', ['lot_number'], unique=False)
    op.create_table('patient_communication_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('do_not_contact_until', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'patient_id', 'channel', name='ux_pcp_clinic_patient_channel')
    )
    op.create_table('patient_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('related_patient_id', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('is_primary_guardian', sa.Boolean(), nullable=False),
    sa.Column('authority', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['related_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'related_patient_id', 'relationship', name='ux_relationship_patient_related_kind')
    )
    op.create_index(op.f('ix_patient_relationships_patient_id'), 'patient_relationships', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_relationships_related_patient_id'), 'patient_relationships', ['related_patient_id'], unique=False)
    op.create_table('provider_compensation_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('commission_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('set_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['set_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_compensation_history_provider_eff', 'provider_compensation_history', ['provider_id', sa.literal_column('effective_date DESC')], unique=False)
    op.create_index(op.f('ix_provider_compensation_history_provider_id'), 'provider_compensation_history', ['provider_id'], unique=False)
    op.create_table('provider_time_off',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_time_off_clinic_id'), 'provider_time_off', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_provider_time_off_provider_id'), 'provider_time_off', ['provider_id'], unique=False)
    op.create_index('ix_provider_time_off_provider_range', 'provider_time_off', ['provider_id', 'start_at', 'end_at'], unique=False)
    op.create_table('tooth_chart_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('surface_notes', sa.JSON(), nullable=True),
    sa.Column('last_examined_at', sa.DateTime(), nullable=True),
    sa.Column('examined_by_user_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['examined_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'patient_id', 'tooth_number', name='ux_tooth_chart_clinic_patient_tooth')
    )
    op.create_index(op.f('ix_tooth_chart_entries_clinic_id'), 'tooth_chart_entries', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tooth_chart_entries_patient_id'), 'tooth_chart_entries', ['patient_id'], unique=False)
    op.create_table('denture_case_implants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('denture_case_id', sa.String(), nullable=False),
    sa.Column('tooth_position', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=False),
    sa.Column('surface_treatment', sa.String(), nullable=True),
    sa.Column('abutment_type', sa.String(), nullable=True),
    sa.Column('placed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['denture_case_id'], ['denture_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denture_case_implants_denture_case_id'), 'denture_case_implants', ['denture_case_id'], unique=False)
    op.create_index(op.f('ix_denture_case_implants_lot_number'), 'denture_case_implants', ['lot_number'], unique=False)
    op.create_table('lab_case_materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lab_case_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('qty_consumed', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('unit_cost', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['lab_case_id'], ['lab_cases.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_case_materials_lab_case_id'), 'lab_case_materials', ['lab_case_id'], unique=False)
    op.create_index(op.f('ix_lab_case_materials_lot_id'), 'lab_case_materials', ['lot_id'], unique=False)
    op.create_table('claim_response_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('affected_service_codes', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['insurance_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_response_codes_claim_id'), 'claim_response_codes', ['claim_id'], unique=False)
    op.create_index('ix_claim_response_codes_claim_severity', 'claim_response_codes', ['claim_id', 'severity'], unique=False)
    op.create_index('ix_appt_reminders_status_due', 'appointment_reminders', ['status', 'scheduled_at'], unique=False)
    op.create_index('ix_appointment_resources_appointment', 'appointment_resources', ['appointment_id'], unique=False)
    op.create_index('ix_appointment_resources_operatory', 'appointment_resources', ['operatory_id'], unique=False)
    op.create_index('ix_appointments_clinic_start', 'appointments', ['clinic_id', sa.literal_column('start_time DESC')], unique=False)
    op.create_index('ix_appointments_clinic_status', 'appointments', ['clinic_id', 'status'], unique=False)
    op.create_index('ix_appointments_patient_start', 'appointments', ['patient_id', sa.literal_column('start_time DESC')], unique=False)
    op.create_index('ix_audit_log_clinic_created', 'audit_log', ['clinic_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_clinical_notes_appointment', 'clinical_notes', ['appointment_id'], unique=False)
    op.create_index('ix_clinical_notes_patient_created', 'clinical_notes', ['patient_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_communications_clinic_created', 'communications', ['clinic_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_communications_patient_created', 'communications', ['patient_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_denture_cases_clinic_status', 'denture_cases', ['clinic_id', 'status'], unique=False)
    op.create_index('ix_denture_cases_patient_status', 'denture_cases', ['patient_id', 'status'], unique=False)
    op.create_index('ix_documents_patient_kind', 'documents', ['patient_id', 'kind'], unique=False)
    op.create_index('ix_claims_clinic_status', 'insurance_claims', ['clinic_id', 'status'], unique=False)
    op.create_index('ix_invoices_clinic_status', 'invoices', ['clinic_id', 'status', 'due_at'], unique=False)
    op.create_index('ix_invoices_patient', 'invoices', ['patient_id'], unique=False)
    op.create_index('ix_lab_cases_clinic_status', 'lab_cases', ['clinic_id', 'status'], unique=False)
    op.create_index('ix_lab_cases_denture_case', 'lab_cases', ['denture_case_id'], unique=False)
    op.create_index('ix_lead_events_lead_created', 'lead_events', ['lead_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('ix_leads_clinic_status', 'leads', ['clinic_id', 'status'], unique=False)
    op.create_index('ix_patient_insurance_patient_primary', 'patient_insurance', ['patient_id', 'is_primary'], unique=False)
    op.create_index('ix_patients_clinic', 'patients', ['clinic_id'], unique=False)
    op.create_index('ix_provider_availability_provider_weekday', 'provider_availability', ['provider_id', 'weekday'], unique=False)
    op.create_index('ix_provider_busy_blocks_provider_weekday', 'provider_busy_blocks', ['provider_id', 'weekday'], unique=False)
    op.create_index('ix_recalls_clinic_due_status', 'recalls', ['clinic_id', 'due_at', 'status'], unique=False)
    op.create_index('ix_recalls_patient_status', 'recalls', ['patient_id', 'status'], unique=False)
    op.create_index('ux_recalls_active_patient_rule', 'recalls', ['patient_id', 'rule_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'sent')"), postgresql_where=sa.text("status IN ('pending', 'sent')"))
    op.create_index('ix_treatment_plans_patient_status', 'treatment_plans', ['patient_id', 'status'], unique=False)
    op.create_index('ix_waitlist_clinic_status', 'waitlist_entries', ['clinic_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_clinic_status', table_name='waitlist_entries')
    op.drop_index('ix_treatment_plans_patient_status', table_name='treatment_plans')
    op.drop_index('ux_recalls_active_patient_rule', table_name='recalls', sqlite_where=sa.text("status IN ('pending', 'sent')"), postgresql_where=sa.text("status IN ('pending', 'sent')"))
    op.drop_index('ix_recalls_patient_status', table_name='recalls')
    op.drop_index('ix_recalls_clinic_due_status', table_name='recalls')
    op.drop_index('ix_provider_busy_blocks_provider_weekday', table_name='provider_busy_blocks')
    op.drop_index('ix_provider_availability_provider_weekday', table_name='provider_availability')
    op.drop_index('ix_patients_clinic', table_name='patients')
    op.drop_index('ix_patient_insurance_patient_primary', table_name='patient_insurance')
    op.drop_index('ix_leads_clinic_status', table_name='leads')
    op.drop_index('ix_lead_events_lead_created', table_name='lead_events')
    op.drop_index('ix_lab_cases_denture_case', table_name='lab_cases')
    op.drop_index('ix_lab_cases_clinic_status', table_name='lab_cases')
    op.drop_index('ix_invoices_patient', table_name='invoices')
    op.drop_index('ix_invoices_clinic_status', table_name='invoices')
    op.drop_index('ix_claims_clinic_status', table_name='insurance_claims')
    op.drop_index('ix_documents_patient_kind', table_name='documents')
    op.drop_index('ix_denture_cases_patient_status', table_name='denture_cases')
    op.drop_index('ix_denture_cases_clinic_status', table_name='denture_cases')
    op.drop_index('ix_communications_patient_created', table_name='communications')
    op.drop_index('ix_communications_clinic_created', table_name='communications')
    op.drop_index('ix_clinical_notes_patient_created', table_name='clinical_notes')
    op.drop_index('ix_clinical_notes_appointment', table_name='clinical_notes')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_clinic_created', table_name='audit_log')
    op.drop_index('ix_appointments_patient_start', table_name='appointments')
    op.drop_index('ix_appointments_clinic_status', table_name='appointments')
    op.drop_index('ix_appointments_clinic_start', table_name='appointments')
    op.drop_index('ix_appointment_resources_operatory', table_name='appointment_resources')
    op.drop_index('ix_appointment_resources_appointment', table_name='appointment_resources')
    op.drop_index('ix_appt_reminders_status_due', table_name='appointment_reminders')
    op.drop_index('ix_claim_response_codes_claim_severity', table_name='claim_response_codes')
    op.drop_index(op.f('ix_claim_response_codes_claim_id'), table_name='claim_response_codes')
    op.drop_table('claim_response_codes')
    op.drop_index(op.f('ix_lab_case_materials_lot_id'), table_name='lab_case_materials')
    op.drop_index(op.f('ix_lab_case_materials_lab_case_id'), table_name='lab_case_materials')
    op.drop_table('lab_case_materials')
    op.drop_index(op.f('ix_denture_case_implants_lot_number'), table_name='denture_case_implants')
    op.drop_index(op.f('ix_denture_case_implants_denture_case_id'), table_name='denture_case_implants')
    op.drop_table('denture_case_implants')
    op.drop_index(op.f('ix_tooth_chart_entries_patient_id'), table_name='tooth_chart_entries')
    op.drop_index(op.f('ix_tooth_chart_entries_clinic_id'), table_name='tooth_chart_entries')
    op.drop_table('tooth_chart_entries')
    op.drop_index('ix_provider_time_off_provider_range', table_name='provider_time_off')
    op.drop_index(op.f('ix_provider_time_off_provider_id'), table_name='provider_time_off')
    op.drop_index(op.f('ix_provider_time_off_clinic_id'), table_name='provider_time_off')
    op.drop_table('provider_time_off')
    op.drop_index(op.f('ix_provider_compensation_history_provider_id'), table_name='provider_compensation_history')
    op.drop_index('ix_provider_compensation_history_provider_eff', table_name='provider_compensation_history')
    op.drop_table('provider_compensation_history')
    op.drop_index(op.f('ix_patient_relationships_related_patient_id'), table_name='patient_relationships')
    op.drop_index(op.f('ix_patient_relationships_patient_id'), table_name='patient_relationships')
    op.drop_table('patient_relationships')
    op.drop_table('patient_communication_preferences')
    op.drop_index(op.f('ix_inventory_lots_lot_number'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_item_id'), table_name='inventory_lots')
    op.drop_index('ix_inventory_lots_clinic_qty', table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_clinic_id'), table_name='inventory_lots')
    op.drop_table('inventory_lots')
    op.drop_index(op.f('ix_inventory_items_clinic_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_human_identifiers_entity', table_name='human_identifiers')
    op.drop_index('ix_human_identifiers_clinic_kind', table_name='human_identifiers')
    op.drop_table('human_identifiers')
    op.drop_index('ix_clinic_sequences_clinic_kind', table_name='clinic_sequences')
    op.drop_table('clinic_sequences')
    op.drop_index(op.f('ix_clinic_operating_hours_clinic_id'), table_name='clinic_operating_hours')
    op.drop_table('clinic_operating_hours')
    op.drop_index('ix_clinic_closures_clinic_start', table_name='clinic_closures')
    op.drop_index(op.f('ix_clinic_closures_clinic_id'), table_name='clinic_closures')
    op.drop_table('clinic_closures')
    # ### end Alembic commands ###
