"""
Service descriptions for all dental services.

This module contains detailed descriptions for each service that can be used
when seeding the database.
"""

SERVICE_DESCRIPTIONS = {
    1: "Professional teeth cleaning to remove plaque, tartar, and stains. Includes polishing and fluoride treatment to maintain healthy teeth and gums.",
    2: "Deep cleaning procedure that removes plaque and tartar from below the gum line. Used to treat gum disease and prevent further progression.",
    3: "Routine dental examination to assess oral health, check for cavities, gum disease, and other dental issues. Includes visual inspection and basic screening.",
    4: "Comprehensive evaluation of oral health including examination of teeth, gums, jaw, and soft tissues. May include X-rays and oral cancer screening.",
    5: "Regular check-up examination for existing patients to monitor oral health and detect any changes or issues since last visit.",
    6: "Application of fluoride to strengthen tooth enamel and prevent cavities. Especially beneficial for children and those at high risk of decay.",
    7: "Protective coating applied to the chewing surfaces of back teeth to prevent cavities. Commonly used for children and teenagers.",
    8: "X-ray images of the upper and lower back teeth to detect cavities between teeth and check bone health. Typically taken during routine check-ups.",
    9: "Complete set of X-rays showing all teeth and supporting structures. Used for comprehensive evaluation and treatment planning.",
    10: "Full-mouth X-ray that shows all teeth, jaws, and surrounding structures in a single image. Useful for overall assessment and planning.",
    11: "X-ray of individual tooth and its root to diagnose issues like infection, abscess, or root problems.",
    12: "Modern X-ray technology using digital sensors instead of film. Provides instant images with lower radiation exposure.",
    13: "3D imaging technology that provides detailed views of teeth, bones, and soft tissues. Essential for implant planning and complex procedures.",
    14: "Traditional silver-colored filling material used to restore decayed teeth. Durable and cost-effective option for back teeth.",
    15: "Tooth-colored filling material that matches natural teeth. Made of composite resin, ideal for visible areas and small to medium cavities.",
    16: "High-quality tooth-colored filling made of ceramic material. Provides excellent aesthetics and durability for larger restorations.",
    17: "Custom-made cap that covers and protects a damaged tooth. Made of porcelain for natural appearance and strength.",
    18: "Dental crown with porcelain exterior and metal interior. Combines strength and aesthetics for durable tooth restoration.",
    19: "Premium crown made of zirconia, one of the strongest and most aesthetic materials. Excellent for both front and back teeth.",
    20: "Traditional crown made of gold alloy. Known for durability and biocompatibility, ideal for back teeth.",
    21: "Fixed dental restoration that replaces one or more missing teeth. Consists of artificial teeth anchored to adjacent natural teeth.",
    22: "Custom-made restoration that fits within the cusps of a tooth. Used to repair moderate damage while preserving healthy tooth structure.",
    23: "Restoration that covers one or more cusps of a tooth. Provides more coverage than an inlay for larger areas of damage.",
    24: "Endodontic treatment for front teeth to remove infected or damaged pulp. Saves the tooth and prevents extraction.",
    25: "Root canal procedure for premolar teeth to treat infection and preserve the natural tooth structure.",
    26: "Root canal treatment for molar teeth, the most complex type due to multiple roots. Essential for saving back teeth.",
    27: "Retreatment of a previously root-canaled tooth that has developed new infection or complications.",
    28: "Surgical procedure to remove the tip of a tooth root and surrounding infected tissue. Performed when root canal treatment is insufficient.",
    29: "Removal of a tooth that is visible and easily accessible. Performed under local anesthesia with minimal recovery time.",
    30: "Tooth extraction requiring surgical techniques, such as cutting gum tissue or removing bone. For impacted or broken teeth.",
    31: "Removal of wisdom teeth (third molars) that may be causing pain, crowding, or other issues. Often performed preventively.",
    32: "Surgical removal of a tooth that is trapped beneath the gum line or bone. Requires specialized techniques and longer recovery.",
    33: "Procedure to add bone material to the jaw to support dental implants or other restorations. Promotes bone regeneration.",
    34: "Surgical procedure to add bone to the upper jaw in the sinus area. Required when there's insufficient bone for implant placement.",
    35: "Treatment for periodontal (gum) disease including deep cleaning, medication, and ongoing maintenance to restore gum health.",
    36: "Surgical procedure to transplant gum tissue to areas where gums have receded. Improves aesthetics and protects tooth roots.",
    37: "Ongoing care for patients with gum disease history. Includes specialized cleaning and monitoring to prevent recurrence.",
    38: "Surgical procedure to reduce deep pockets around teeth caused by gum disease. Helps prevent tooth loss and improves oral health.",
    39: "Professional teeth whitening performed in the dental office using high-concentration bleaching agents. Provides immediate, dramatic results.",
    40: "Take-home teeth whitening kit with custom trays and professional-grade bleaching gel. Convenient option for gradual whitening at home.",
    41: "Thin porcelain shells bonded to the front of teeth to improve appearance. Used for discolored, chipped, or misaligned teeth.",
    42: "Composite resin material applied to teeth to improve appearance. More affordable alternative to porcelain veneers with good results.",
    43: "Application of tooth-colored composite resin to repair chips, gaps, or discoloration. Quick and effective cosmetic treatment.",
    44: "Surgical reshaping of gum tissue to create a more even and attractive gum line. Improves smile aesthetics.",
    45: "Initial consultation to evaluate orthodontic needs, discuss treatment options, and create a personalized treatment plan.",
    46: "Traditional metal braces system to straighten teeth and correct bite issues. Most common and effective orthodontic treatment.",
    47: "Clear, removable aligner system to straighten teeth without visible braces. Popular alternative for adults and teens.",
    48: "Custom-made device worn after braces to maintain teeth in their new positions and prevent shifting.",
    49: "Regular appointments during braces treatment to adjust wires, bands, and ensure proper tooth movement progress.",
    50: "Complete set of removable artificial teeth to replace all natural teeth in upper or lower jaw. Restores function and appearance.",
    51: "Partial set of artificial teeth to replace some missing teeth. Attaches to remaining natural teeth for stability.",
    52: "Procedure to refit existing dentures for better comfort and function. Needed as jaw shape changes over time.",
    53: "Repair of broken or damaged dentures to restore function. Common repairs include fixing cracks, replacing teeth, or adjusting fit.",
    54: "Initial consultation to evaluate candidacy for dental implants, discuss options, and create treatment plan.",
    55: "Surgical placement of a titanium implant post into the jawbone to replace a missing tooth root. Foundation for a permanent tooth replacement.",
    56: "Custom-made crown that attaches to a dental implant. Provides a natural-looking and functional replacement tooth.",
    57: "Gentle teeth cleaning specifically designed for children. Includes education on proper oral hygiene habits.",
    58: "Dental examination tailored for children to check development, detect issues early, and ensure healthy oral growth.",
    59: "Removal of a baby tooth that is damaged, infected, or preventing permanent tooth eruption. Performed with special care for children.",
    60: "Device placed to maintain space for permanent teeth when a baby tooth is lost prematurely. Prevents crowding and alignment issues.",
    61: "Urgent dental care for immediate problems like severe pain, trauma, or infection. Available for same-day treatment.",
    62: "Treatment for tooth pain including diagnosis, pain relief, and addressing the underlying cause of discomfort.",
    63: "Emergency repair of a broken or fractured tooth to restore function and prevent further damage.",
    64: "Replacement or reattachment of a lost filling or crown. Restores tooth protection and prevents sensitivity or further damage.",
    65: "Treatment for temporomandibular joint (TMJ) disorders including pain, clicking, or limited jaw movement. May involve splints, therapy, or medication.",
    66: "Evaluation for sleep apnea and snoring issues. Includes examination and discussion of oral appliance options for treatment.",
    67: "Visual and manual examination to detect early signs of oral cancer. Includes checking lips, tongue, gums, and throat.",
    68: "Mild sedative gas (nitrous oxide) administered during treatment to help patients relax and reduce anxiety. Safe and effective for all ages.",
    69: "Intravenous sedation for patients with severe anxiety or complex procedures. Provides deep relaxation while remaining conscious.",
    70: "General consultation appointment for patients who are unsure of their specific dental needs or require an initial evaluation to determine the appropriate treatment. The dentist will assess the patient's oral health and recommend the best course of action.",
}
